# Docker Compose file for StockPredictAI
version: '3.8'

services:
  stockpredictai:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - ALPHA_VANTAGE_API_KEY=M7NBIFRKDLBBSW9B
      - FINNHUB_API_KEY=cvnlqo1r01qq3c7g47l0cvnlqo1r01qq3c7g47lg
      - NEWS_API_KEY=6b5313bb7df747f391cbc252459d5d84
      - CACHE_TTL_REALTIME=120
      - API_CALL_LIMIT_PER_MIN=10
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s